### ISSUE TITLE
./unittest fails with sklearn >= 0.24.0

### ISSUE THREAD

**Issue by cosmin** [Netflix/vmaf#945] opened 2021-11-20 06:34 UTC
I got VMAF up and running on a new workstation, and trying to run `./unittest` results in failures due to being unable to find `sklearn.ensemble.forest`, which has been renamed to `sklearn.ensemble._forest`. 

I verified that `0.23.2` is the last version of `scikit-learn` in which `sklearn.ensemble.forest` is available rather than `sklearn.ensemble._forest`

This would be somewhat trivial to work around in code, trying to import one and falling back to the other on import error. However the reference is actually inside a couple of serialized models.

```
model/other_models/nflx_vmaff_rf_v1.pkl
model/other_models/nflx_vmaff_rf_v2.pkl
```

One option is to pin the version in requirements.txt to 0.23.2, the other would be to pin the version to `>= 0.24.0` and redo the serialized models so they can pick up the reference to the new module name.

**Comment by li-zhi** [comment] 2021-12-20 19:38
@cosmin sorry for getting back after a month. I tried sklearn 0.24.0 and 1.0.1 and I was unable to reproduce the issue above. Which tests failed?

**Comment by nilfm** [comment] 2023-07-27 16:40
Closing this since there haven't been updates in a long time. Feel free to reopen as needed.

**Closed by nilfm** 2023-07-27 16:40 UTC
