### ISSUE TITLE
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by yuanCabaal** [Netflix/vmaf#585] opened 2020-06-05 16:48 UTC
Hi,
when I was trying to run the command "pip3 install --user ."  get the error in the title for: Building wheel for vmaf (setup.py) ... error
Running setup.py install for vmaf ... error

I followed closely the instruction of vmaf. Are there other packages that I have to install besides the ones mentioned in the documentation?

Thanks

**Comment by yuanCabaal** [comment] 2020-06-07 14:22
python-wheel is already installed. Are you suggesting to use a different package instead of python-wheel?

**Comment by ChengHan111** [comment] 2020-06-12 00:05
I also got the same question about that. I wandering if there is a more specific answer to that? Thank you

**Comment by 1480c1** [comment] 2020-06-12 00:12
my best answer would be to try to see if your system differentiates between pip, pip2, and pip3, and make sure you have the right package for the pip you are using, for example, if `pip --version` returns something like `(python 3.*)` at the end, that signals to me that your distro's default python version is 3, so you would just look for `python-wheel` in your package manager, however, if your system does not default to python 3 with its packages, you would need to look for something like `python3-wheel`.

I personally do not use the python side of vmaf and pretty much only use the libvmaf and vmafossexec provided, which only requires running make or using meson+ninja directly.

@li-zhi might have a better answer for your problem since he seems to be the main person modifying the python scripts

**Comment by ChengHan111** [comment] 2020-06-12 00:17
I actually thinking I am facing this problem then I double check to make sure I have got python3-wheel already. Also I am in python 3.6.9 dev as well. Though my pip --version is in python2.7 I use pip3 all the time. Still facing the problem though

**Comment by 1480c1** [comment] 2020-06-12 00:19
Can you give me details such as what distro+version and what exact commands you used starting from git clone or download so I can try to reproduce?

**Comment by ChengHan111** [comment] 2020-06-12 00:29
Thank you for helping me.
Here place the code:

git clone https://github.com/Netflix/vmaf.git
cd vmaf
cd python

sudo apt-get update -qq && \
sudo apt-get install -y \
  python3 \
  python3-dev \
  python3-pip \
  python3-setuptools \
  python3-wheel \
  python3-tk

pip3 install --user .

I get stuck at --user . The error code is above the same as @yuanCabaal mentioned four days ago.
Running in Ubuntu 18.04.4 LTS with python 3.6-dev (in python3.6.9)

**Comment by 1480c1** [comment] 2020-06-12 15:36
```bash
apt update
apt install git g{cc,++} python3{,-{dev,pip,setuptools,wheel,tk}}
git clone https://github.com/Netflix/vmaf.git
cd vmaf/python
pip3 install cython
pip3 install -r requirements.txt
pip3 install --user .
```
does indeed reproduce the results.

It seems it might stem from the file `python/vmaf/core/adm_dwt2_cy.pyx` and the way pip builds stuff.

It seems the generated c file gets placed in a random pip temp dir under `/tmp/pip-<random-hash>-build` and it does not seem to call gcc from the current folder, so `../../../libvmaf/src/feature/adm_tools.c` would not produce the correct path

**Comment by 1480c1** [comment] 2020-06-12 15:37
I do not know enough about python, setuptools, and cython to be able to code a fix for this right now

**Comment by 1480c1** [comment] 2020-06-12 15:39
It seems running
```bash
python3 setup.py install
```
works though

**Comment by ChengHan111** [comment] 2020-06-12 16:25
I first run python3 setup.py install generating a c.file then pip3 install --user . gets no error. But still there is a problem when I try to run the testing part. When I run './unitest', there is still assertionerror, which says the vmaff_rc does not exist. And the testing part is almost all fail or error. I am wandering there might be something wrong when doing the setup.py process.
Here is my procedure:
apt update
apt install git g{cc,++} python3{,-{dev,pip,setuptools,wheel,tk}}
git clone https://github.com/Netflix/vmaf.git
cd vmaf/python
pip3 install cython
pip3 install -r requirements.txt
python3 setup.py install
pip3 install --user . 

Then cd to the repository root and run 
./unitest

This process still goes wrong, would u please run this line to double check for me? Thank you

**Comment by 1480c1** [comment] 2020-06-12 16:36
You need to run make in the vmaf directory with meson and ninja installed

**Comment by ChengHan111** [comment] 2020-06-12 17:15
Okay I get this! I successfully run the test after I update my ninja! Thank you so much! This helps a lot!

**Comment by yuanCabaal** [comment] 2020-06-13 13:54
Do you have to run make first and then install the python code?

**Comment by 1480c1** [comment] 2020-06-13 15:00
The make command was only needed because he wanted to run the unit tests

**Comment by nasirhemed** [comment] 2020-06-15 20:47
I was able to set it up using `python setup.py install` but I was facing a couple of issues: 

- The binaries are not added in pip3's local packages
- I am not able to run pip3 install --user . after running `python setup.py install`
- I am getting the following error when I run `vmaf/python/vmaf/script/run_vmaf.py`

```
Traceback (most recent call last):
  File "vmaf/python/vmaf/script/run_vmaf.py", line 164, in <module>
    ret = main()
  File "vmaf/python/vmaf/script/run_vmaf.py", line 124, in main
    runner.run()
  File "/home/rtc-video-quality/.env/lib/python3.7/site-packages/vmaf/core/executor.py", line 155, in run
    self.results = list(map(self._run_on_asset, self.assets))
  File "/home/rtc-video-quality/.env/lib/python3.7/site-packages/vmaf/core/quality_runner.py", line 335, in _run_on_asset
    vmaf_fassembler = self._get_vmaf_feature_assembler_instance(asset)
  File "/home/rtc-video-quality/.env/lib/python3.7/site-packages/vmaf/core/quality_runner.py", line 310, in _get_vmaf_feature_assembler_instance
    feature_dict = self._load_model(asset).get_appended_info('feature_dict')
  File "/home/rtc-video-quality/.env/lib/python3.7/site-packages/vmaf/core/quality_runner.py", line 446, in _load_model
    format(filepath=model_filepath, cls=train_test_model_class.__name__, e=e))
AssertionError: File /home/rtc-video-quality/.env/lib/python3.7/model/vmaf_v0.6.1.pkl may not be a valid model file for class LibsvmNusvrTrainTestModel: File name /home/rtc-video-quality/.env/lib/python3.7/model/vmaf_v0.6.1.pkl does not exist.
```

**Comment by slhck** [comment] 2020-06-16 07:04
@li-zhi Any idea what was changed that broke the Python build? I also cannot install the Dockerfile anymore:

```
[115/115] c++  -o test/test_predict 'test/9f86d08@@test_predict@exe/test.c.o' 'test/9f86d08@@test_predict@exe/test_predict.c.o' 'test/9f86d08@@test_predict@exe/.._src_predict.c.o' 'test/9f86d08@@test_predict@exe/.._src_feature_feature_collector.c.o' 'test/9f86d08@@test_predict@exe/.._src_model.c.o' 'test/9f86d08@@test_predict@exe/.._src_svm.cpp.o' 'test/9f86d08@@test_predict@exe/.._src_unpickle.cpp.o' 'src/25a6634@@ptools@sha/third_party_ptools_m2pythontools.cc.o' 'src/25a6634@@ptools@sha/third_party_ptools_valpython.cc.o' 'src/25a6634@@ptools@sha/third_party_ptools_midassocket.cc.o' 'src/25a6634@@ptools@sha/third_party_ptools_valprotocol2.cc.o' 'src/25a6634@@ptools@sha/third_party_ptools_m2ser.cc.o' 'src/25a6634@@ptools@sha/third_party_ptools_m2streamdataenc.cc.o' 'src/25a6634@@ptools@sha/third_party_ptools_m2convertrep.cc.o' 'src/25a6634@@ptools@sha/third_party_ptools_timeconv.cc.o' -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -pthread
cd python && python3 setup.py build_ext --build-lib .
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    from Cython.Build import cythonize
ModuleNotFoundError: No module named 'Cython'
make: *** [all] Error 1
Makefile:2: recipe for target 'all' failed
The command '/bin/sh -c cd /vmaf && make clean && make' returned a non-zero code: 
```

It seems this is related to the Cython requirement, and running `make` requires `cython`, even though it is only installed *later* when installing the Python requirements...

**Comment by slhck** [comment] 2020-06-16 07:10
You can reproduce this issue with the following Dockerfile. Note that the installation of the requirements has been moved up before `make` so that Cython will be available:

```Dockerfile
FROM ubuntu:18.04

# setup timezone
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# get and install building tools
RUN apt-get update && \
	apt-get install -y --no-install-recommends \
        build-essential \
        git \
        ninja-build \
        doxygen \
        python3 \
        python3-dev \
        python3-pip \
        python3-setuptools \
        python3-wheel \
        python3-tk \
        && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists

# retrieve source code
COPY . /vmaf

# install python requirements
RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir meson
RUN pip3 install --no-cache-dir -r /vmaf/python/requirements.txt

# setup environment
ENV PATH=/vmaf:/vmaf/libvmaf/build/tools:$PATH

# make vmaf
RUN cd /vmaf && make clean && make

# install python tools
RUN pip3 install --no-cache-dir /vmaf/python

WORKDIR /root/
```

Fails with:

```
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -I../libvmaf/src -I/usr/include/python3.6m -c vmaf/core/adm_dwt2_cy.c -o build/temp.linux-x86_64-3.6/vmaf/core/adm_dwt2_cy.o
    In file included from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1832:0,
                     from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from vmaf/core/adm_dwt2_cy.c:627:
    /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it with " \
      ^~~~~~~
    vmaf/core/adm_dwt2_cy.c:630:10: fatal error: ../../../libvmaf/src/feature/adm_tools.c: No such file or directory
     #include "../../../libvmaf/src/feature/adm_tools.c"
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-0cidqy8g/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-0cidqy8g/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ei9a21xh/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/vmaf Check the logs for full command output.
The command '/bin/sh -c pip3 install --no-cache-dir /vmaf/python' returned a non-zero code: 1
```

**Comment by nasirhemed** [comment] 2020-06-16 13:44
I'm running into the same issue if i run `pip install --user /vmaf/python` for the first time as well. If I run `python /vmaf/python/setup.py`, the process works but the binaries aren't installed

**Comment by wallw-bits** [comment] 2020-07-28 18:30
`git bisect` reports that the breaking commit (at least for the docker build) was https://github.com/Netflix/vmaf/commit/25d4b8380d05529ead0c9fd381f8a070f458cbfc

**Comment by slhck** [comment] 2020-07-29 08:34
@li-zhi Any idea how this can be reverted? The easiest fix may be to have users install Cython manually before attempting to compile libvmaf and pip-install the Python library.

**Closed** 2024-03-14 21:45 UTC
