### ISSUE TITLE
Problem in reading y4m files

### ISSUE THREAD

**Issue by JoshuaEbenezer** [Netflix/vmaf#889] opened 2021-08-04 21:00 UTC
y4m_input.c in libvmaf/tools has an error in reading the headers of y4m files. Line 565 reads the header for 80 characters or until "\n" is reached:
``` 
 /*Read until newline, or 80 cols, whichever happens first.*/
  for(i=0;i<79;i++)
  ```

  The problem is that there is no reason why a y4m header should be less than 80 characters (afaik). I have a y4m file with a long header (more than 80 characters). A quick fix would be increasing this limit to 100.

  ``` 
  char buffer[100];
  int  ret;
  int  i;
  int  xstride;
  /*Read until newline, or 100 cols, whichever happens first.*/
  for(i=0;i<99;i++){ 
    ret=fread(buffer+i,1,1,_fin);
    if(ret<1)return -1;
    if(buffer[i]=='\n')break;
  }
  ```

**Comment by 1480c1** [comment] 2021-08-04 23:24
aom (uses similar code for y4m input) has some different changes

https://aomedia.googlesource.com/aom/+/dfcb5ff4dd7df0c3aa65da1d1b6e697c87292481%5E%21/#F0
https://aomedia.googlesource.com/aom/+/06023aeaff79e6215c69f3b93b9c740f022ee1c4%5E%21/#F0
https://aomedia.googlesource.com/aom/+/cff8ac586150c23fc10712be601af422c41fa8a7%5E%21/#F0
https://aomedia.googlesource.com/aom/+log/refs/heads/master/common/y4minput.c

**Comment by 1480c1** [comment] 2021-08-05 18:23
Also duplicate of https://github.com/Netflix/vmaf/issues/825

**Comment by JoshuaEbenezer** [comment] 2021-08-06 01:14
Yes. The AOM fix is cleaner. Looks like #825 wasn't resolved so I'm leaving this open until the change is made.

**Comment by kylophone** [comment] 2021-08-06 16:19
@JoshuaEbenezer Can you please trying reading your y4m with #890 applied? It's a quick fix, but it should work.

**Comment by JoshuaEbenezer** [comment] 2021-08-06 19:37
yes it works. I didn't do it with #890 , I just defined the header limit as 100 myself. #890 defines the limit as 256, so I did it again with 256 and it works.

**Closed** 2021-08-10 19:17 UTC
