### ISSUE TITLE
FFmpeg filter libvmaf use too much memory

### ISSUE THREAD

**Issue by fanyingming** [Netflix/vmaf#144] opened 2018-01-14 01:21 UTC
I use FFmpeg filter libvmaf like:
ffmpeg -i 1.mp4 -i 2.mp4 -lavfi "libvmaf" -f null -
I noticed that the memory FFmpeg used is almost 2x of YUV.
While run_vmaf and ffmpeg2vmaf no such issue.

**Comment by LigH-de** [comment] 2018-01-14 13:58
Duplicate of #143

**Closed** 2018-04-04 01:35 UTC
