### ISSUE TITLE
Cuda Docker build failing

### ISSUE THREAD

**Issue by vaisest** [Netflix/vmaf#1328] opened 2024-02-06 21:39 UTC
The Dockerfile seems to try to install "cpython" with pip, but as far as I can tell this isn't a real package name and the build fails on this step. If I remove "cpython" the build seems to work until the `ffmpeg` build:

```
=> ERROR [ 8/10] RUN cd FFmpeg && ./configure     --enable-libnpp     --enable-nonfr  7.6s 
------                                                                                      
 > [ 8/10] RUN cd FFmpeg && ./configure     --enable-libnpp     --enable-nonfree     --enable-nvdec     --enable-nvenc     --enable-cuvid     --enable-cuda     --enable-cuda-nvcc     --enable-libvmaf     --enable-ffnvcodec     --disable-stripping     --extra-cflags="-I/usr/local/cuda/include"     --extra-ldflags="-L/usr/local/cuda/lib64 -L/usr/local/cuda/lib64/stubs/":
7.529 ERROR: libvmaf >= 2.0.0 not found using pkg-config
7.530 
7.530 If you think configure made a mistake, make sure you are using the latest
7.530 version from Git.  If the latest version fails, report the problem to the
7.530 ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
7.532 Include the log file "ffbuild/config.log" produced by configure as this will help
7.532 solve the problem.
------
Dockerfile.cuda:21
--------------------
  20 |     # install ffmpeg
  21 | >>> RUN cd FFmpeg && ./configure \
  22 | >>>     --enable-libnpp \
  23 | >>>     --enable-nonfree \
  24 | >>>     --enable-nvdec \
  25 | >>>     --enable-nvenc \
  26 | >>>     --enable-cuvid \
  27 | >>>     --enable-cuda \
  28 | >>>     --enable-cuda-nvcc \
  29 | >>>     --enable-libvmaf \
  30 | >>>     --enable-ffnvcodec \
  31 | >>>     --disable-stripping \
  32 | >>>     --extra-cflags="-I/usr/local/cuda/include" \
  33 | >>>     --extra-ldflags="-L/usr/local/cuda/lib64 -L/usr/local/cuda/lib64/stubs/" 
  34 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cd FFmpeg && ./configure     --enable-libnpp     --enable-nonfree     --enable-nvdec     --enable-nvenc     --enable-cuvid     --enable-cuda     --enable-cuda-nvcc     --enable-libvmaf     --enable-ffnvcodec     --disable-stripping     --extra-cflags=\"-I/usr/local/cuda/include\"     --extra-ldflags=\"-L/usr/local/cuda/lib64 -L/usr/local/cuda/lib64/stubs/\"" did not complete successfully: exit code: 1
```

This happens on both my Windows desktop and Linux laptop.

**Comment by kylophone** [comment] 2024-02-07 01:21
cc @gedoensmax

**Comment by gedoensmax** [comment] 2024-02-07 10:54
Thanks for pinging me Kyle. Not sure how that `cpython` survived my docker test runs 🤔 While I have seen this pkgconfig error before I have not seen it inside docker. Just reran the Dockerfile on my machine with a few updates and did not need the ldconfig line. Could you give it another try with the PR and if it does not work on your side without the line I'll add it.

**Comment by vaisest** [comment] 2024-02-07 14:37
> Thanks for pinging me Kyle. Not sure how that `cpython` survived my docker test runs 🤔 While I have seen this pkgconfig error before I have not seen it inside docker. Just reran the Dockerfile on my machine with a few updates and did not need the ldconfig line. Could you give it another try with the PR and if it does not work on your side without the line I'll add it.

I was unable to build this new Dockerfile without `RUN DEBIAN_FRONTEND=noninteractive apt-get install -y nvidia-cuda-toolkit`. I was also unable to run it ("ffmpeg: error while loading shared libraries: libvmaf.so.3: cannot open shared object file: No such file or directory") until I added:
```
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/x86_64-linux-gnu/
RUN ldconfig
```
 
Now I'm getting an error like this from ffmpeg:

```
ffmpeg version N-113561-ge05d3c1a16 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: --enable-libnpp --enable-nonfree --enable-nvdec --enable-nvenc --enable-cuvid --enable-cuda --enable-cuda-nvcc --enable-libvmaf --enable-ffnvcodec --disable-stripping --extra-cflags=-I/usr/local/cuda/include --extra-ldflags='-L/usr/local/cuda/lib64 -L/usr/local/cuda/lib64/stubs/'
  libavutil      58. 36.101 / 58. 36.101
  libavcodec     60. 39.100 / 60. 39.100
  libavformat    60. 20.100 / 60. 20.100
  libavdevice    60.  4.100 / 60.  4.100
  libavfilter     9. 17.100 /  9. 17.100
  libswscale      7.  6.100 /  7.  6.100
  libswresample   4. 13.100 /  4. 13.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/data/ref.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.3.100
  Duration: 00:07:47.55, start: 0.000000, bitrate: 359693 kb/s
  Stream #0:0[0x1](und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 2560x1440 [SAR 1:1 DAR 16:9], 359548 kb/s, 60 fps, 60 tbr, 16k tbn (default)
      Metadata:
        handler_name    : VideoHandler
        vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from '/data/dis.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.3.100
  Duration: 00:07:47.55, start: 0.000000, bitrate: 66615 kb/s
  Stream #1:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 2560x1440 [SAR 1:1 DAR 16:9], 66468 kb/s, 60 fps, 60 tbr, 16k tbn (default)
      Metadata:
        handler_name    : VideoHandler
        vendor_id       : [0][0][0][0]
        encoder         : Lavc60.31.102 h264_nvenc
  Stream #1:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 (h264) -> libvmaf_cuda (graph 0)
  Stream #1:0 (h264) -> libvmaf_cuda (graph 0)
  libvmaf_cuda:default (graph 0) -> Stream #0:0 (wrapped_avframe)
  Stream #0:1 -> #0:1 (aac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
[h264 @ 0x563c48c85100] decoder->cvdl->cuvidCreateDecoder(&decoder->decoder, params) failed -> CUDA_ERROR_INVALID_VALUE: invalid argument
[h264 @ 0x563c48c85100] Using more than 32 (37) decode surfaces might cause nvdec to fail.
[h264 @ 0x563c48c85100] Try lowering the amount of threads. Using 16 right now.
[h264 @ 0x563c48c85100] Failed setup for format cuda: hwaccel initialisation returned error.
[h264 @ 0x563c49a66f80] decoder->cvdl->cuvidCreateDecoder(&decoder->decoder, params) failed -> CUDA_ERROR_INVALID_VALUE: invalid argument
[h264 @ 0x563c49a66f80] Using more than 32 (37) decode surfaces might cause nvdec to fail.
[h264 @ 0x563c49a66f80] Try lowering the amount of threads. Using 16 right now.
[h264 @ 0x563c49a66f80] Failed setup for format cuda: hwaccel initialisation returned error.
Impossible to convert between the formats supported by the filter 'graph 0 input from stream 0:0' and the filter 'auto_scale_0'
[fc#0 @ 0x563c47968800] Error reinitializing filters!
[fc#0 @ 0x563c47968800] Task finished with error code: -38 (Function not implemented)
[fc#0 @ 0x563c47968800] Terminating thread with return code -38 (Function not implemented)
[vost#0:0/wrapped_avframe @ 0x563c4a78bc00] Could not open encoder before EOF
[vost#0:0/wrapped_avframe @ 0x563c4a78bc00] Task finished with error code: -22 (Invalid argument)
[vost#0:0/wrapped_avframe @ 0x563c4a78bc00] Terminating thread with return code -22 (Invalid argument)
[out#0/null @ 0x563c4a78b100] Nothing was written into output file, because at least one of its streams received no packets.
frame=    0 fps=0.0 q=0.0 Lsize=       0KiB time=N/A bitrate=N/A speed=N/A    
Conversion failed!
```

**Comment by gedoensmax** [comment] 2024-02-07 15:08
Are you able to run `sudo docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi` in your environment ? It sounds odd that you have to install `nvidia-cuda-toolkit` in a CUDA container. 
For the FFmpeg command I have to say I am not an expert. You have to make sure that the filter chain is built correctly to accommodate for the output being e.g. NV12 and then being converted to YUV420. See here:
https://github.com/Netflix/vmaf/blob/346e176d939174b9bcd8d749189ec4e54a01ef74/resource/doc/docker.md?plain=1#L55-L56

**Comment by kylophone** [comment] 2024-02-07 19:21
Merged #1330.

**Comment by gedoensmax** [comment] 2024-02-08 08:00
> I didn't provide any settings to ffmpeg myself, and the two videos are yuv420p. It's entirely possible I'm doing something wrong, but in that case I don't know what

For 420 you will have to insert the mentioned `scale_cuda` filter as Nvdec outputs NV12 which is an interleaved version of yuv and to support VMAF it has to be converted to planar.

I am more surprised that you have to run `apt install nvidia-cuda-toolkit` can you share a full docker log ?

**Comment by vaisest** [comment] 2024-02-08 14:16
> For 420 you will have to insert the mentioned `scale_cuda` filter as Nvdec outputs NV12 which is an interleaved version of yuv and to support VMAF it has to be converted to planar.
> 
> I am more surprised that you have to run `apt install nvidia-cuda-toolkit` can you share a full docker log ?

Build from master (`docker build -f Dockerfile.cuda --no-cache --progress=plain . 2>&1 | tee build_toolkit.log`): https://gist.github.com/vaisest/fa2847315e024056b4e6ea5a5dacb551

With nvidia-cuda-toolkit and LD_LIBRARY_PATH: https://gist.github.com/vaisest/cbbc4e4db8b3be18d8efe357548becd1

I also finally managed to solve the run issue. It seems to be related to this: https://forums.developer.nvidia.com/t/nvdec-fails-on-file-requires-29-threads-surfaces-thus-fails-on-3-threads/240827

I had to reduce the thread so this is the changes needed to run it on my system at least:

```
$ git diff Dockerfile.cuda
diff --git a/Dockerfile.cuda b/Dockerfile.cuda
index 47f5a0f7..0958409f 100644
--- a/Dockerfile.cuda
+++ b/Dockerfile.cuda
@@ -7,6 +7,8 @@ FROM nvidia/cuda:$CUDA_VERSION-devel-ubuntu22.04
 RUN DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y libopenjp2-7-dev \
     ninja-build cmake git python3 python3-pip nasm xxd pkg-config curl unzip
 
+RUN DEBIAN_FRONTEND=noninteractive apt-get install -y nvidia-cuda-toolkit
+
 RUN git clone https://github.com/Netflix/vmaf.git && cd vmaf && git checkout $VMAF_TAG
 
 RUN git clone https://github.com/FFmpeg/FFmpeg.git && cd FFmpeg && git checkout $FFFMPEG_TAG
@@ -39,7 +41,7 @@ RUN cd FFmpeg && make -j && make install
 RUN mkdir /data
 # VMAF+decode GPU (only works for NVDec supported formats https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new)
 ENTRYPOINT ["ffmpeg" ,"-hwaccel", "cuda", "-hwaccel_output_format" ,"cuda", \
-    "-i" ,"/data/ref.mp4", \
-    "-hwaccel", "cuda", "-hwaccel_output_format", "cuda", \
+    "-threads", "1", "-i" ,"/data/ref.mp4", \
+    "-threads", "1", "-hwaccel", "cuda", "-hwaccel_output_format", "cuda", \
     "-i", "/data/dis.mp4"  ,\
-    "-filter_complex", "[0:v][1:v]libvmaf_cuda" ,"-f" ,"null", "-"]
+    "-filter_complex", "[0:v]scale_cuda=format=yuv420p[ref];[1:v]scale_cuda=format=yuv420p[dist];[ref][dist]libvmaf_cuda" ,"-f" ,"null", "-"]
\ No newline at end of file
```

Thread count up to 11 seemed to work for my 3060 Ti. Since I have a 5800X3D it must have defaulted to 16 which was too much.

**Comment by gedoensmax** [comment] 2024-02-08 14:22
> Build from master (docker build -f Dockerfile.cuda --no-cache --progress=plain . 2>&1 | tee build_toolkit.log):

This log shows that VMAF can find cuda etc. The problem really seems to be that PKG_CONFIG is not found. No idea why this happens in your build I am not able to reproduce this. 
Maybe add: `ENV PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/x86_64-linux-gnu/pkgconfig` ?

**Closed** 2024-02-24 04:51 UTC

**Comment by AlanIWBFT** [comment] 2025-05-07 04:46
If you are using podman (which is based on CDI) like me, you may be facing the same issue of pkg-config cannot configure libvmaf.so >= 2.0.0. The real reason is when compiling the test program of libvmaf, the linker can't find libcuda.so.1. It, however, really doesn't exist in the container during the podman build time. It is later injected into the container by nvidia-container-toolkit, along with a new ld config into /etc/ld.so.conf.d. That means the compilation of ffmpeg must be delayed until you run the container for the first time. Not so great, but this is a way that can make it work.
