### ISSUE TITLE
Ffmpeg+libvmaf examples

### ISSUE THREAD

**Issue by christosbampis** [Netflix/vmaf#413] opened 2019-12-11 02:42 UTC
Placeholder to add some documentation on ffmpeg+libvmaf examples.

**Comment by slhck** [comment] 2019-12-13 20:01
Do you need some input/help on this? There are a few lines here: https://github.com/Netflix/vmaf/blob/master/resource/doc/libvmaf.md#use-libvmafa-with-ffmpeg – but there could of course be more examples, e.g. on how to parse the stats or use different options/models.

**Comment by li-zhi** [comment] 2019-12-13 21:17
We have some recent experience with this and will share a page soon. The
key things to use FFmpeg+libvmaf is to make sure 1) PTS is correctly
aligned and 2) the correct upsampling algorithm is used (need to explicitly
specify bicubic upsampling, since by default bilinear is used).

**Comment by christosbampis** [comment] 2019-12-14 00:21
Sure, all help and input is useful! We will make a PR with the documentation and then feel free to suggest improvements and give feedback.

**Comment by 1480c1** [comment] 2019-12-23 02:05
Perhaps for windows ffmpeg+libvmaf, someone could mention that the `model_path` needs to be in a "mixed mode" like `libvmaf=model_path=C\\:/vmaf/share/model/vmaf_v0.6.1.pkl` with the `:` escaped and the `\` escaped to escape the `:` for ffmpeg to accept it as an argument to model_path instead of splitting it

**Comment by slhck** [comment] 2019-12-23 10:26
@1480c1 Good idea. See the open PR #423 where I already left a few comments.

**Comment by slhck** [comment] 2020-07-15 11:43
@1480c1 Do you have any idea what could cause the issue here? https://github.com/slhck/ffmpeg-quality-metrics/issues/10

We've tried all kinds of combinations of specifying the VMAF model path under Windows, when called from Python, but it's not working. What sort of escaping needs to be used when generating the command line with, say, `C:/test.pkl` from Python?

**Comment by 1480c1** [comment] 2020-07-15 14:09
hmm

there's a few issues I could see, and some ways I can think of "fixing" them.

assuming the average windows user doesn't know about needing to escape parts of a path in windows and they may try doing `Copy as path` or tabbing a whole path, you may first want to resolve the pkl file to an absolute path, that way you are only going to be doing any string manipulation on a sort of known format.

Next, then open using the `$abspath` to check, also check `${abspath}.model`

next, after you confirmed that python's standard functions can fopen them correctly, then convert the windows path to a "mixed" path using `/` as the path sep. I personally don't do any python scripting because of how convoluted the distributions are on windows and prefer bash, so I am not aware of any standard function in python, but in terms of bash, it might be as simple as 
```bash
tr '\\' '/'
```
or `cygpath -m "$path"` to get a path like `C:/media-autobuild_suite-master/.gitignore`, that way you don't have to worry about any further escaping of the slashes.

next, when passing that path to FFmpeg, you will need to escape the `:` for FFmpeg since it uses that as an option separator, I used `\\` to escape it, but I do not remember anymore if that was due to my shell, or if I needed to escape the first `\` for the second `\` to be passed to the code, but the general idea is to escape the `:` so FFmpeg doesn't interpret it as a separator


example path from `Copy as path` and tabbing in both cmd.exe and powershell: "C:\media-autobuild_suite-master\.gitignore"


example reason why I sometimes hate windows/python combo
```c
#include <stdio.h>

int main(int argc, char **argv) {
    for (int i = 0; i < argc; ++i)
        printf(": %s :\n", argv[i]);
}
```
```python
import subprocess
import os
import sys

cmd = [
        "./a.exe", "C:/temp", "C\:/temp", "C\\:/temp"
]

process = subprocess.Popen(cmd)
```

using msys2's python under `/usr/bin/python.exe`
results
```none
: C:\media-autobuild_suite-master\msys64\home\cddeg\a.exe :
: C:/temp :
: C\;C:\media-autobuild_suite-master\msys64\temp :
: C\;C:\media-autobuild_suite-master\msys64\temp :
```
using mingw-w64 python under `/mingw64/bin/python.exe`
```none
: ./a.exe :
: C:/temp :
: C\:/temp :
: C\:/temp :
```

**Comment by li-zhi** [comment] 2020-10-04 23:58
We have a page with more FFmpeg+libvmaf examples:
https://github.com/Netflix/vmaf/blob/master/resource/doc/ffmpeg.md

@1480c1 Would you like to add a section to the page on special instructions for Windows usages?

**Comment by 1480c1** [comment] 2020-10-05 01:03
I could try adding a note on the bottom about the model path on windows

**Comment by li-zhi** [comment] 2020-10-05 16:36
That would be helpful. Thank you.

**Comment by nilfm** [comment] 2023-07-27 13:03
Closing this issue as part of a clean-up.

**Closed by nilfm** 2023-07-27 13:03 UTC
