### ISSUE TITLE
Can I complete transcoding and computing VMAF score in one single command?

### ISSUE THREAD

**Issue by RonLu** [Netflix/vmaf#206] opened 2018-08-07 08:00 UTC
Hi,
To compute the VMAF score of a video using FFmpeg, normally, I think the process is of three steps:
step1: transcode the origin video into the distorted video;
step2: transcode the distorted video to be of the same resolution with the origin video;
step3: compute the VMAF score of the distorted video using ffmpeg -lavfi libvmaf command.

Is my understanding correct?

And is it possible that I can complete transcoding and computing VMAF score in one single ffmpeg command?
That is to combine the above 3 steps into one single step?

Thanks for the answer in advance!

**Comment by kylophone** [comment] 2018-08-07 17:51
With FFmpeg at least, generally it's a two step operation.

https://stackoverflow.com/questions/45729010/ffmpeg-feeding-output-of-encode-operation-to-filter

**Comment by slhck** [comment] 2018-08-08 09:46
There is no such option for VMAF, as it is an external library, and thus available through the respective filter only, once ffmpeg is compiled with support for it.

If you would like such an option for ffmpeg, VMAF would have to be added as a core function in `ffmpeg`, which is a little unlikely as it's 1) an ever-changing model (unlike PSNR), 2) much more complex to calculate (PSNR is just a few lines of code in `ffmpeg.c`), and 3) quite a bit of work that doesn't really pay off, as encoding and then calculating VMAF is probably not much slower (unless you have really slow IO).

Either way that is not a feature request for this repository, but rather for FFmpeg, so it should go on https://trac.ffmpeg.org/

**Comment by kylophone** [comment] 2018-08-08 17:30
I'm going to close this issue for now. Feel free to @ me if you have any more questions about this.

**Closed by kylophone** 2018-08-08 17:30 UTC

**Comment by vans163** [comment] 2021-05-08 13:08
`as encoding and then calculating VMAF is probably not much slower`

This is not really true, the problem is to calculate VMAF you need to decode the original source video, and when you down sample videos, the decode is the slowest part of the whole thing.  If you need to calculate VMAF for multiple outputs (of the same source) it gets even slower, since your paying the decode cost over and over. The reason the entire source video needs to be decoded even if n_samples is used is to get frame index accuracy between 2 separately encoded videos is not possible without decoding from start to finish, seeking does not work (probably possibly to write a algo to seek but its out of scope).
