### ISSUE TITLE
libvmaf ERROR vmaf_predict_score_at_index()

### ISSUE THREAD

**Issue by Yassine-Bouksaier** [Netflix/vmaf#1367] opened 2024-05-22 11:08 UTC
I'll be scoring between each frame of 2 YUV raw videos. When I select 'vmaf_4k_v0.6.1.json' as the model, the scores are calculated. However, when I use version=vmaf_4k_v0.6.1 as the model, only the first score is calculated, and there's an error with the second score:

VMAF version b24c3d68
1 frame ⢀⠀ 0.00 FPS vmaf_4k_v0.6.1: 100.000000
2 frames ⡀⠀ 0.00 FPS libvmaf ERROR vmaf_predict_score_at_index(): no feature 'VMAF_integer_feature_motion2_score' at index1
Frame 2: issue generating pooled VMAF score

**Comment by nilfm99** [comment] 2024-05-22 19:31
Hi @Yassine-Bouksaier, that is unexpected. Could you please share the sources and command you used so we can investigate this on our end?

**Comment by nilfm99** [comment] 2024-05-23 17:17
Sorry, I don't understand what that code from `vmaf.c` has to do with the issue.

On the command you posted below: I tried the following:
```
➜  vmaf git:(master) ✗ vmaf -r ../inputs/ref5.y4m -d ../inputs/dis5.y4m
VMAF version 3.0.0
5 frames ⡂⠀ 0.00 FPS
vmaf_v0.6.1: 7.341517
➜  vmaf git:(master) ✗ vmaf -r ../inputs/ref5.y4m -d ../inputs/dis5.y4m --model version=vmaf_4k_v0.6.1
VMAF version 3.0.0
5 frames ⡂⠀ 0.00 FPS
vmaf_4k_v0.6.1: 28.612129
```

and both succeeded. It would be useful to know:
1. what is `./quality` - is it an alias for the `vmaf` executable?
2. what is in `/home/yassine/quality/pipe5` and `/home/yassine/quality/pipe6` - how do you generate those files?

**Comment by Yassine-Bouksaier** [comment] 2024-05-24 08:03
1. ./quality is an executable for a program named quality.c, which is very similar to vmaf.c but calculates the score between every two frames of the same index. The score calculation loop occurs right after the extraction of a single image from the video, as indicated in the previous code section.
2. /home/yassine/quality/pipe5 and /home/yassine/quality/pipe6 are raw videos in the yuv4mpeg format generated with ffmpeg.

**Comment by nilfm99** [comment] 2024-06-20 18:59
Sorry I missed this. If you could provide the input files themselves, or anything that could help reproduce this on our end, that would be helpful. 

> ./quality is an executable for a program named quality.c, which is very similar to vmaf.c but calculates the score between every two frames of the same index. 

I see, so the main difference between this and `vmaf.c` is that you want to get the quality results for each frame as it is computed, rather than at the end, is that correct?

**Comment by nilfm99** [comment] 2024-06-27 00:52
Hi @Yassine-Bouksaier, I was able to reproduce your issue ([here](https://github.com/Netflix/vmaf/compare/repro-1367?expand=1) is a branch that reproduces it with a simple change), and the root of it is that you are requesting `vmaf_score_at_index` for a picture index that cannot be computed yet (each frame has a temporal dependency on the next one due to the `motion2` feature, see [here](https://github.com/Netflix/vmaf/blob/8cc78aff7855e8fec934e56275a2a59c2d794749/libvmaf/src/feature/integer_motion.c#L406-L408)). What you can do is delay the `vmaf_score_at_index` call by one frame: when you have just read frame 1, request the score for frame 0, and so on. When you read the last frame, the feature extractor will be flushed and you can get the final score. This will allow you to get the scores almost in real time, with just a single frame delay.

cc @kylophone and @christosbampis for any more observations

**Comment by nilfm99** [comment] 2024-07-02 19:25
Closing this issue for now, please do not hesitate to reopen if you run into more problems.

**Closed by nilfm99** 2024-07-02 19:25 UTC
