### ISSUE TITLE
/usr/bin/env: 'python': Permission denied

### ISSUE THREAD

**Issue by haozhenxiao** [Netflix/vmaf#430] opened 2020-01-09 09:04 UTC
I'm trying to run vmaf docker following [this](https://github.com/Netflix/vmaf/blob/master/resource/doc/docker.md), after building the images, when running `docker run --rm vmaf run_vmaf`, I got error `/usr/bin/env: 'python': Permission denied`.

**Comment by slhck** [comment] 2020-01-09 10:09
I could reproduce this. Apparently with the removal of Python 2, this no longer works. Preparing a PR.

**Comment by haozhenxiao** [comment] 2020-01-09 10:46
@slhck cool, does any old version work? I can check out a old commit.

**Comment by slhck** [comment] 2020-01-09 12:04
No, the issue seems to be that the base Ubuntu image changed its behavior at some point.

You can try: https://github.com/Netflix/vmaf/pull/431

**Comment by kylophone** [comment] 2020-01-09 17:32
Closing, since #431 was merged. Should fix this, if it doesn't feel free to ping, or re-open.

**Closed by kylophone** 2020-01-09 17:32 UTC

**Comment by davidwarford** [comment] 2020-10-20 19:04
@kylophone Sorry to ping on such an old issue but I'm having a similar issue on master with the build command `./build.sh -p webgl release`
full console output is as follows
```
/build.sh -p webgl release
Warning: JAVA_HOME is not set, skipping Java projects
Building release in out/cmake-release...
-- The C compiler identification is Clang 7.0.1
-- The CXX compiler identification is Clang 7.0.1
-- Check for working C compiler: /usr/bin/clang-7
-- Check for working C compiler: /usr/bin/clang-7 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++-7
-- Check for working CXX compiler: /usr/bin/clang++-7 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- The ASM compiler identification is Clang
-- Found assembler: /usr/bin/clang-7
-- DFG LUT size set to 128x128
-- Found Python3: /usr/bin/python3.8 (found version "3.8.2") found components: Interpreter
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.2", minimum required is "3")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nix/filament/out/cmake-release
[93/676] Generate extended instruction tables for spv-amd-shader-explicit-vertex-parameter.
FAILED: third_party/spirv-tools/spv-amd-shader-explicit-vertex-parameter.insts.inc
cd /home/nix/filament/out/cmake-release/third_party/spirv-tools/source && /home/nix/filament/third_party/spirv-tools/utils/generate_grammar_tables.py --extinst-vendor-grammar=/home/nix/filament/third_party/spirv-tools/source/extinst.spv-amd-shader-explicit-vertex-parameter.grammar.json --vendor-insts-output=/home/nix/filament/out/cmake-release/third_party/spirv-tools/spv-amd-shader-explicit-vertex-parameter.insts.inc --vendor-operand-kind-prefix=
/usr/bin/env: ‘python’: Permission denied
[94/676] Generate extended instruction tables for spv-amd-shader-trinary-minmax.
FAILED: third_party/spirv-tools/spv-amd-shader-trinary-minmax.insts.inc
cd /home/nix/filament/out/cmake-release/third_party/spirv-tools/source && /home/nix/filament/third_party/spirv-tools/utils/generate_grammar_tables.py --extinst-vendor-grammar=/home/nix/filament/third_party/spirv-tools/source/extinst.spv-amd-shader-trinary-minmax.grammar.json --vendor-insts-output=/home/nix/filament/out/cmake-release/third_party/spirv-tools/spv-amd-shader-trinary-minmax.insts.inc --vendor-operand-kind-prefix=
/usr/bin/env: ‘python’: Permission denied
[96/676] Generate extended instruction tables for spv-amd-gcn-shader.
FAILED: third_party/spirv-tools/spv-amd-gcn-shader.insts.inc
cd /home/nix/filament/out/cmake-release/third_party/spirv-tools/source && /home/nix/filament/third_party/spirv-tools/utils/generate_grammar_tables.py --extinst-vendor-grammar=/home/nix/filament/third_party/spirv-tools/source/extinst.spv-amd-gcn-shader.grammar.json --vendor-insts-output=/home/nix/filament/out/cmake-release/third_party/spirv-tools/spv-amd-gcn-shader.insts.inc --vendor-operand-kind-prefix=
/usr/bin/env: ‘python’: Permission denied
[97/676] Update build-version.inc in the SPIRV-Tools build directory (if necessary).
FAILED: third_party/spirv-tools/build-version.inc
cd /home/nix/filament/out/cmake-release/third_party/spirv-tools/source && /home/nix/filament/third_party/spirv-tools/utils/update_build_version.py /home/nix/filament/third_party/spirv-tools /home/nix/filament/out/cmake-release/third_party/spirv-tools/build-version.inc
/usr/bin/env: ‘python’: Permission denied
[102/676] Building CXX object filament/backend/CMakeFiles/backend.dir/src/vulkan/VulkanDriver.cpp.o
ninja: build stopped: subcommand failed.```

**Comment by thesudhindra** [comment] 2022-03-22 16:23
If you’re in Git Bash, please check the python executable location by run `which python.`

If the executable is under `~/AppData/Local/Microsoft/WindowsApps/`, then it’s a link to Windows AppStore, not a real one.

Please install python manually and update this in your `PATH` environment variable.
