### ISSUE TITLE
Unused copy to CPU for CUDA feature extraction

### ISSUE THREAD

**Issue by gedoensmax** [Netflix/vmaf#1167] opened 2023-02-13 17:20 UTC
@kylophone 
I just noticed that this line is responsible for making a redundant copy to the CPU even when there are no registered CPU feature extractors. Do you have the bandwidth to look into fixing this ? It seems to be a performance bottleneck. 
https://github.com/Netflix/vmaf/blob/e81d12e75629f6f0730077bfa7e28764c41b2907/libvmaf/src/libvmaf.c#L553

**Comment by gedoensmax** [comment] 2023-02-13 17:31
One wait would be to introduce a CPU FEX flag 🤔 or to "count" the occurence of flags and then check if all FEX are CUDA for example. I am also able to make a PR but would like to hear your opinion on this.

**Comment by kylophone** [comment] 2023-02-13 17:32
Yes, I can take a look. The intention was to copy data only when both CPU/GPU feature extractors are registered. Did you see this with the `vmaf` command-line tool or in the libvmaf ffmpeg filter? Can you share a command-line I can use to reproduce?

**Comment by gedoensmax** [comment] 2023-02-13 17:42
I used ffmpeg filter and used 2 mp4 files as input (HEVC 420) with -hwaccel and -hwaccel_output set to cuda. Then just do a filter complex between the two and discard the output via -f null -.
An FFmpeg filter patch can be found in the perf mail i sent. Sorry for the sparse details but i just left the office for today!

**Comment by gedoensmax** [comment] 2023-02-15 00:53
```./build_x64_shared/bin/ffmpeg -hwaccel cuda -hwaccel_output_format cuda -i ./data/input.mp4 -hwaccel cuda -hwaccel_output_format cuda -i ./data/output.mp4 -filter_complex "[0:v][1:v]libvmaf_cuda" -f null -```
This is the command line i am using and the old filer implementation i have is attached. I was made aware of the downloads when using Nsight Systems on FFmpeg.

[vf_libvmaf_cuda.txt](https://github.com/Netflix/vmaf/files/10738069/vf_libvmaf_cuda.txt)

**Comment by kylophone** [comment] 2023-02-16 19:02
@gedoensmax found the issue, will send a fix soon. If you want to gather ffmpeg benchmarks in the meantime just change `translate_picture_device()` to return 0 always, that should be equivalent to the intended behavior.

**Comment by kylophone** [comment] 2023-02-22 18:49
@gedoensmax sent a PR for this here: #1170. If you have a second, could you double-check this on your end?

**Comment by kylophone** [comment] 2023-02-23 18:03
Fixed by #1170.

**Closed by kylophone** 2023-02-23 18:03 UTC
