### ISSUE TITLE
ImportError when running unittest and run_testing.py

### ISSUE THREAD

**Issue by NagabhushanSN95** [Netflix/vmaf#550] opened 2020-04-17 02:30 UTC
Hi,
I'm trying to get VMAF predictions on a set of videos. When I run `run_testing.py`, I'm getting output, graph and all. But there are some lines saying `ImportError`. Is this okay or did I miss something?

On deeper inspection, the error is caused in `config.py` file on line 26 `from . import externals`, because there is no file named `externals` in `vmaf-1.5.1/python/src`.

I get the same error when running `./unittest` also. The output of `unittest` is as follows:
```
Ran 321 tests in 611.990s

OK (skipped=1)
```

**Comment by slhck** [comment] 2020-04-17 04:52
Duplicate of  #541

**Comment by slhck** [comment] 2020-04-20 18:26
Should be fixed in `master`, please check.

**Closed** 2020-10-02 23:37 UTC
