### ISSUE TITLE
-Wstringop-truncation build warning

### ISSUE THREAD

**Issue by AdelKS** [Netflix/vmaf#1228] opened 2023-08-19 23:00 UTC
Hello,

When compiling on Linux with GCC 13.2, I get these warnings:

```
 * ../vmaf-2.3.1/libvmaf/src/model.c:129:9: warning: ‘__builtin_strncpy’ specified bound depends on the length of the source argument [-Wstringop-truncation]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1108:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1110:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1112:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1114:17: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1121:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1123:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1125:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1127:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1139:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1141:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1143:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1145:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1157:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1159:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1161:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1163:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1175:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1177:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1179:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1181:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1190:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1194:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1196:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1198:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1200:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1207:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1209:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1211:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1213:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1225:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1227:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1229:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1231:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1243:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1245:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1247:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1249:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1261:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1263:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1265:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1267:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1275:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1279:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1281:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1283:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1285:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1292:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1294:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1296:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1298:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1310:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1312:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1314:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1316:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1328:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1330:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1332:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1334:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1347:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1349:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1351:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1353:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1362:33: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1713:37: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1716:37: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1720:37: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1723:37: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1727:37: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
 * ../vmaf-2.3.1/libvmaf/src/feature/x86/vif_avx2.c:1731:21: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
```

which may need to be fixed.

Thanks!

**Comment by nilfm** [comment] 2023-08-21 15:56
Thank you for reporting this! We'll take a look.

**Comment by nilfm** [comment] 2023-08-22 15:08
I've tried to reproduce this, and I see these warnings come up when compiling v2.3.1 (which I think is what you did based on your command line output) but not on the master branch. Are you seeing this happen in the master branch too?

**Comment by AdelKS** [comment] 2023-08-22 16:02
Hello,

Thank you for looking into it ! And apologies, I haven't tried master: indeed, it does not have the incompatible pointer type issues any  longer. Other than the warnings you are probably already aware of (I can list them here or in a separate issue if you wish).

Only one severe warning is left on master:
```
../libvmaf-9999/libvmaf/src/model.c:136:9: warning: ‘__builtin_strncpy’ specified bound depends on the length of the source argument [-Wstringop-truncation]
```

Another question: would you have a look at LTO compile issues, due to `-Werror=lto-type-mismatch` ? I can open a separate bug report or just post it here.

**Comment by nilfm** [comment] 2023-08-22 20:11
I see, thanks again for the details. Tagging @kylophone FYI. I think it makes sense to wait a little bit until we solve the build issue (#1204) so we have the tests running to safeguard any changes.

**Comment by nilfm99** [comment] 2024-01-11 16:46
> Another question: would you have a look at LTO compile issues, due to `-Werror=lto-type-mismatch` ? I can open a separate bug report or just post it here.

I haven't been able to reproduce these warnings/errors, could you please specify your platform and command lines to reproduce?

**Comment by AdelKS** [comment] 2024-01-11 21:16
Hello, thanks for coming back to this.

The LTO flags I used are `-flto -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing`

Here's the error on latest commit `32c27d7`

```
FAILED: src/libvmaf.so.3.0.0 
x86_64-pc-linux-gnu-g++  -o src/libvmaf.so.3.0.0 src/libvmaf.so.3.0.0.p/meson-generated_.._vmaf_v0.6.1.json.c.o src/libvmaf.so.3.0.0.p/meson-generated_.._vmaf_b_v0.6.3.json.c.o src/libvmaf.so.3.0.0.p/meson-generated_.._vmaf_v0.6.1neg.json.c.o src/libvmaf.so.3.0.0.p/meson-generated_.._vmaf_4k_v0.6.1.json.c.o src/libvmaf.so.3.0.0.p/meson-generated_.._vmaf_4k_v0.6.1neg.json.c.o src/libx86_avx2.a.p/feature_common_convolution_avx.c.o src/libx86_avx2.a.p/feature_x86_motion_avx2.c.o src/libx86_avx2.a.p/feature_x86_vif_avx2.c.o src/libx86_avx2.a.p/feature_x86_adm_avx2.c.o src/libx86_avx2.a.p/feature_x86_cambi_avx2.c.o src/libx86_avx512.a.p/feature_x86_motion_avx512.c.o src/libx86_avx512.a.p/feature_x86_vif_avx512.c.o src/liblibvmaf_feature.a.p/feature_picture_copy.c.o src/liblibvmaf_feature.a.p/feature_integer_psnr.c.o src/liblibvmaf_feature.a.p/feature_third_party_xiph_psnr_hvs.c.o src/liblibvmaf_feature.a.p/feature_feature_extractor.c.o src/liblibvmaf_feature.a.p/feature_feature_name.c.o src/liblibvmaf_feature.a.p/feature_alias.c.o src/liblibvmaf_feature.a.p/feature_integer_adm.c.o src/liblibvmaf_feature.a.p/feature_feature_collector.c.o src/liblibvmaf_feature.a.p/feature_integer_motion.c.o src/liblibvmaf_feature.a.p/feature_integer_vif.c.o src/liblibvmaf_feature.a.p/feature_ciede.c.o src/liblibvmaf_feature.a.p/feature_common_alignment.c.o src/liblibvmaf_feature.a.p/feature_mkdirp.c.o src/liblibvmaf_feature.a.p/feature_float_ssim.c.o src/liblibvmaf_feature.a.p/feature_float_ms_ssim.c.o src/liblibvmaf_feature.a.p/feature_ssim.c.o src/liblibvmaf_feature.a.p/feature_ms_ssim.c.o src/liblibvmaf_feature.a.p/feature_iqa_decimate.c.o src/liblibvmaf_feature.a.p/feature_iqa_ssim_tools.c.o src/liblibvmaf_feature.a.p/feature_iqa_math_utils.c.o src/liblibvmaf_feature.a.p/feature_iqa_convolve.c.o src/liblibvmaf_feature.a.p/feature_cambi.c.o src/liblibvmaf_feature.a.p/feature_luminance_tools.c.o src/liblibvmaf_feature.a.p/feature_null.c.o src/liblibvmaf_cpu.a.p/cpuid.obj src/liblibvmaf_cpu.a.p/cpu.c.o src/liblibvmaf_cpu.a.p/x86_cpu.c.o src/libvmaf.so.3.0.0.p/libvmaf.c.o src/libvmaf.so.3.0.0.p/predict.c.o src/libvmaf.so.3.0.0.p/model.c.o src/libvmaf.so.3.0.0.p/svm.cpp.o src/libvmaf.so.3.0.0.p/picture.c.o src/libvmaf.so.3.0.0.p/mem.c.o src/libvmaf.so.3.0.0.p/output.c.o src/libvmaf.so.3.0.0.p/fex_ctx_vector.c.o src/libvmaf.so.3.0.0.p/thread_pool.c.o src/libvmaf.so.3.0.0.p/dict.c.o src/libvmaf.so.3.0.0.p/opt.c.o src/libvmaf.so.3.0.0.p/ref.c.o src/libvmaf.so.3.0.0.p/read_json_model.c.o src/libvmaf.so.3.0.0.p/pdjson.c.o src/libvmaf.so.3.0.0.p/log.c.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libvmaf.so.3 -O3 -march=native -pipe -fno-plt -flto -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -flto -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -Wl,-O1 -Wl,--as-needed -pthread -lm -Wl,--end-group
../libvmaf-9999/libvmaf/src/model.c:41:19: error: type of ‘src_vmaf_4k_v0_6_1neg_json’ does not match original declaration [-Werror=lto-type-mismatch]
   41 | extern const char src_vmaf_4k_v0_6_1neg_json;
      |                   ^
src/vmaf_4k_v0.6.1neg.json.c:1:15: note: ‘src_vmaf_4k_v0_6_1neg_json’ was previously declared here
    1 | unsigned char src_vmaf_4k_v0_6_1neg_json[] = {
      |               ^
../libvmaf-9999/libvmaf/src/model.c:39:19: error: type of ‘src_vmaf_4k_v0_6_1_json’ does not match original declaration [-Werror=lto-type-mismatch]
   39 | extern const char src_vmaf_4k_v0_6_1_json;
      |                   ^
src/vmaf_4k_v0.6.1.json.c:1:15: note: ‘src_vmaf_4k_v0_6_1_json’ was previously declared here
    1 | unsigned char src_vmaf_4k_v0_6_1_json[] = {
      |               ^
../libvmaf-9999/libvmaf/src/model.c:37:19: error: type of ‘src_vmaf_v0_6_1neg_json’ does not match original declaration [-Werror=lto-type-mismatch]
   37 | extern const char src_vmaf_v0_6_1neg_json;
      |                   ^
src/vmaf_v0.6.1neg.json.c:1:15: note: ‘src_vmaf_v0_6_1neg_json’ was previously declared here
    1 | unsigned char src_vmaf_v0_6_1neg_json[] = {
      |               ^
../libvmaf-9999/libvmaf/src/model.c:35:19: error: type of ‘src_vmaf_b_v0_6_3_json’ does not match original declaration [-Werror=lto-type-mismatch]
   35 | extern const char src_vmaf_b_v0_6_3_json;
      |                   ^
src/vmaf_b_v0.6.3.json.c:1:15: note: ‘src_vmaf_b_v0_6_3_json’ was previously declared here
    1 | unsigned char src_vmaf_b_v0_6_3_json[] = {
      |               ^
../libvmaf-9999/libvmaf/src/model.c:33:19: error: type of ‘src_vmaf_v0_6_1_json’ does not match original declaration [-Werror=lto-type-mismatch]
   33 | extern const char src_vmaf_v0_6_1_json;
      |                   ^
src/vmaf_v0.6.1.json.c:1:15: note: ‘src_vmaf_v0_6_1_json’ was previously declared here
    1 | unsigned char src_vmaf_v0_6_1_json[] = {
      |               ^
lto1: some warnings being treated as errors
lto-wrapper: fatal error: x86_64-pc-linux-gnu-g++ returned 1 exit status
compilation terminated.
/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
[72/72] x86_64-pc-linux-gnu-g++  -o tools/vmaf tools/vmaf.p/vmaf.c.o tools/vmaf.p/cli_parse.c.o tools/vmaf.p/y4m_input.c.o tools/vmaf.p/vidinput.c.o tools/vmaf.p/yuv_input.c.o -Wl,--as-needed -Wl,--no-undefined -O3 -march=native -pipe -fno-plt -flto -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -flto -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -Wl,-O1 -Wl,--as-needed -Wl,--start-group src/libvmaf.a -pthread -lm -Wl,--end-group
FAILED: tools/vmaf 
x86_64-pc-linux-gnu-g++  -o tools/vmaf tools/vmaf.p/vmaf.c.o tools/vmaf.p/cli_parse.c.o tools/vmaf.p/y4m_input.c.o tools/vmaf.p/vidinput.c.o tools/vmaf.p/yuv_input.c.o -Wl,--as-needed -Wl,--no-undefined -O3 -march=native -pipe -fno-plt -flto -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -flto -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -Wl,-O1 -Wl,--as-needed -Wl,--start-group src/libvmaf.a -pthread -lm -Wl,--end-group
../libvmaf-9999/libvmaf/src/model.c:41:19: error: type of ‘src_vmaf_4k_v0_6_1neg_json’ does not match original declaration [-Werror=lto-type-mismatch]
   41 | extern const char src_vmaf_4k_v0_6_1neg_json;
      |                   ^
src/vmaf_4k_v0.6.1neg.json.c:1:15: note: ‘src_vmaf_4k_v0_6_1neg_json’ was previously declared here
    1 | unsigned char src_vmaf_4k_v0_6_1neg_json[] = {
      |               ^
../libvmaf-9999/libvmaf/src/model.c:39:19: error: type of ‘src_vmaf_4k_v0_6_1_json’ does not match original declaration [-Werror=lto-type-mismatch]
   39 | extern const char src_vmaf_4k_v0_6_1_json;
      |                   ^
src/vmaf_4k_v0.6.1.json.c:1:15: note: ‘src_vmaf_4k_v0_6_1_json’ was previously declared here
    1 | unsigned char src_vmaf_4k_v0_6_1_json[] = {
      |               ^
../libvmaf-9999/libvmaf/src/model.c:37:19: error: type of ‘src_vmaf_v0_6_1neg_json’ does not match original declaration [-Werror=lto-type-mismatch]
   37 | extern const char src_vmaf_v0_6_1neg_json;
      |                   ^
src/vmaf_v0.6.1neg.json.c:1:15: note: ‘src_vmaf_v0_6_1neg_json’ was previously declared here
    1 | unsigned char src_vmaf_v0_6_1neg_json[] = {
      |               ^
../libvmaf-9999/libvmaf/src/model.c:35:19: error: type of ‘src_vmaf_b_v0_6_3_json’ does not match original declaration [-Werror=lto-type-mismatch]
   35 | extern const char src_vmaf_b_v0_6_3_json;
      |                   ^
src/vmaf_b_v0.6.3.json.c:1:15: note: ‘src_vmaf_b_v0_6_3_json’ was previously declared here
    1 | unsigned char src_vmaf_b_v0_6_3_json[] = {
      |               ^
../libvmaf-9999/libvmaf/src/model.c:33:19: error: type of ‘src_vmaf_v0_6_1_json’ does not match original declaration [-Werror=lto-type-mismatch]
   33 | extern const char src_vmaf_v0_6_1_json;
      |                   ^
src/vmaf_v0.6.1.json.c:1:15: note: ‘src_vmaf_v0_6_1_json’ was previously declared here
    1 | unsigned char src_vmaf_v0_6_1_json[] = {
      |               ^
lto1: some warnings being treated as errors
lto-wrapper: fatal error: x86_64-pc-linux-gnu-g++ returned 1 exit status
```

**Comment by nilfm99** [comment] 2024-01-12 21:13
I tracked these errors down: they come up because we use `xxd` to hexdump the model JSON files into C arrays, and those arrays are generated as:

```
unsigned char ___model_vmaf_b_v0_6_3_json[] = {
    ...
}
```

We are declaring those variables as:

```
extern const char src_vmaf_float_v0_6_1neg_json
```

There are two differences:
1. `char` vs `unsigned char`
2. `char` vs `char[]`

Apparently the only fix needed to clear the error is (2), which I implemented in #1310. Fixing (1) would require a change in the public API, concretely `vmaf_read_json_model_from_buffer` and `vmaf_read_json_model_collection_from_buffer`, and I'd rather not do that if we can avoid it.

Would you agree @AdelKS?

**Comment by AdelKS** [comment] 2024-01-14 22:41
Hello @nilfm99 thanks for your feedback ! 

I tested your change in #1310 and indeed the LTO issue is fixed ! I also do not see the `__builtin_strncpy` warning, good job!

> 1. char vs unsigned char

I had a deep look at this not too long ago and conversion between them is relatively safe if I remember well, at least in the sense that the binary representation stays the same. And actually, even on overflow on signed operations, the result is equal if the overflow was done with unsigned integers with the same binary representation (as if `-fwrapv` was given to the compiler).

All this to say, it should be fine to keep it as-is, and the compiler doesn't complain anyway :D

**Comment by nilfm99** [comment] 2024-01-26 18:31
Thank you very much @AdelKS for raising this issue, I believe it's all done now, having merged both PRs. Closing this, please reopen if needed.

**Closed by nilfm99** 2024-01-26 18:31 UTC
