### ISSUE TITLE
inf fps value on low-resolution streams

### ISSUE THREAD

**Issue by Kr1eg3** [Netflix/vmaf#1114] opened 2022-11-11 11:55 UTC
Hello! 

I encountered a problem when calculating psnr on QCIF streams. When calculating psnr for low resolution streams in .json dump in the field fps gets incorrect value "inf". Moreover, this error does not appear all the time, but occurs randomly. 
I attached the archive with the dump file and two test streams. I want to note that this error is repeated not only for 422 color space, but also for 420, 444.

<img width="268" alt="Screen Shot 2022-11-11 at 15 49 04" src="https://user-images.githubusercontent.com/50653532/201334812-5ab6db38-be4a-4b12-80ab-7a6b27a7d88e.png">

I hope I described it correctly  =) 

Command line: 
```
C:\vmaf-install\bin\vmaf.exe -r MissionControlClip3_176x144_60_422_8bit.yuv -d MissionControlClip3_176x144_80_422_8bit.hevc.yuv -w 176 -h 144 -p 422 -b 8 -o vmaf_dump.json --json -n --feature psnr
```

[Files to recreate error.zip](https://github.com/Netflix/vmaf/files/9989972/Files.to.recreate.error.zip)

**Comment by nilfm** [comment] 2022-11-15 16:06
Hi! I am unfortunately unable to reproduce your issue on my laptop: I consistently get very high FPS numbers on that output (in the order of 20,000), but never `inf`. Could you please checkout [this branch](https://github.com/Netflix/vmaf/tree/issue1114_test), build, run, and report the info it prints to screen when the problem occurs?

I think this is simply a problem with `clock()` having finite accuracy and returning the same value at the start/end of the feature computation, which is indeed "infinite FPS".

**Comment by Kr1eg3** [comment] 2022-11-17 15:43
Hi nilfm! I heard your answer and tried to build this branch on the machine, but ran into a bug on the meson side :D I wrote them a ticket today, so I will wait for their response in order not to change the state of the computer to be able to reproduce the error. I will try it on the other machines I have and report back to you.

**Comment by chAlices** [comment] 2022-12-02 12:05
Hi all!
I also have the same problem. When i try to read this output json it will occur a decode error
`json.decoder.JSONDecodeError: Expecting value: line 3 column 10 (char 33)`
And this is because of this line "fps" : inf
I think it should be
`"fps" : "inf" `
That will be better :)

**Comment by nilfm** [comment] 2022-12-02 22:14
Hi @Kr1eg3 and @chAlices, thanks for pointing this out. I put up a PR addressing this by outputting `null` instead of `inf` (which is consistent with how we output floats in other cases). That should give you valid JSON on the output, you can treat it as a special case in your code. You can check out the branch and see if it helps (I can't reproduce the issue on my machine).

**Comment by nilfm** [comment] 2022-12-06 21:34
Merged the changes, this should be fixed now. Just make sure to take into account that `fps` can be `null` in this corner case if you are parsing the output JSON.

**Comment by nilfm** [comment] 2022-12-07 17:13
Closing this as it seems resolved, if the problem remains do let us know and I'll reopen.

**Closed by nilfm** 2022-12-07 17:13 UTC
