### ISSUE TITLE
something wrong when training a new model

### ISSUE THREAD

**Issue by Wangld5** [Netflix/vmaf#1201] opened 2023-07-26 02:40 UTC
When I run `run_vmaf_training.py`，I get the following problems. Does anyone know how to fix it?
![image](https://github.com/Netflix/vmaf/assets/30035015/8bed0d20-91cb-4cbd-93dd-62aba49919cb)
![image](https://github.com/Netflix/vmaf/assets/30035015/5e5d258a-b7d6-4063-9594-1eb14781ec30)

**Comment by Wangld5** [comment] 2023-07-27 01:03
How can I use the flag to enable float features? Do I use the following command ?
`meson build --buildtype release -Denable_float=true`

**Comment by Wangld5** [comment] 2023-07-27 01:07
What‘s more, I run the command according to the [document](https://github.com/Netflix/vmaf/blob/master/resource/doc/python.md), which does not mention that I need to build VMAF

**Comment by nilfm** [comment] 2023-07-27 11:12
Got it, the `make` command in that document is the step that builds VMAF, and it should apply `-Denable_float=true` automatically, see [here](https://github.com/Netflix/vmaf/blob/master/Makefile#L2).

I am unable to reproduce this on ubuntu 18; following the steps on the document you linked results in successful training.

To further debug, could you provide the following information?
* Platform you're working on
* Output of the following command, executed from the source of this repo:
```
meson configure libvmaf/build/ | grep enable_float
```
The second column in that output will be either `true` or `false`, and you need it to be `true` to load float features.

Finally, try removing `--cache-result` from the training command, it will remove a possible source of confusion.

**Comment by Wangld5** [comment] 2023-07-29 01:30
I have solved the issue. Thank you for your help!

**Comment by nilfm** [comment] 2023-07-29 12:24
great to hear that! closing this issue, then

**Closed by nilfm** 2023-07-29 12:24 UTC
